"""drop scans.debug_path

Revision ID: 35c162409d67
Revises: 8a5fea39ade8
Create Date: 2026-09-21 17:06:10.543120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '35c162409d67'
down_revision = '8a5fea39ade8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'debug_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('debug_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
