"""add checked image path/url to submissions

Revision ID: 980422e12355
Revises: df221253c582
Create Date: 2026-09-09 22:08:05.107106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '980422e12355'
down_revision = 'df221253c582'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('checked_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submissions', sa.Column('checked_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'checked_image_url')
    op.drop_column('submissions', 'checked_image_path')
    # ### end Alembic commands ###
