"""simplify question_paper_variants to a per-variant correct label

Revision ID: df221253c582
Revises: fa7cf1fb401e
Create Date: 2026-09-07 19:15:57.501265

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df221253c582'
down_revision = 'fa7cf1fb401e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_paper_variants', sa.Column('correct_option_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'question_paper_variants', ['worksheet_id', 'question_paper_code', 'question_id'])
    op.drop_column('question_paper_variants', 'option_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_paper_variants', sa.Column('option_order', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question_paper_variants', type_='unique')
    op.drop_column('question_paper_variants', 'correct_option_label')
    # ### end Alembic commands ###
