"""add scans table and scan_reviews.scan_id

Revision ID: 8a5fea39ade8
Revises: 7e9ecd69fc7a
Create Date: 2026-09-19 13:29:50.462224

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a5fea39ade8'
down_revision = '7e9ecd69fc7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dewarped_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('debug_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checked_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('worksheet_id', sa.Integer(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('roll_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_paper_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vision_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_correlation_id'), 'scans', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_scans_submission_id'), 'scans', ['submission_id'], unique=False)
    op.create_index(op.f('ix_scans_worksheet_id'), 'scans', ['worksheet_id'], unique=False)
    op.add_column('scan_reviews', sa.Column('scan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scan_reviews_scan_id'), 'scan_reviews', ['scan_id'], unique=False)
    op.create_foreign_key('fk_scan_reviews_scan_id', 'scan_reviews', 'scans', ['scan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_scan_reviews_scan_id', 'scan_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_scan_reviews_scan_id'), table_name='scan_reviews')
    op.drop_column('scan_reviews', 'scan_id')
    op.drop_index(op.f('ix_scans_worksheet_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_submission_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_correlation_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
