"""add correlation_id to scan_reviews

Revision ID: d299d5c1ae95
Revises: 980422e12355
Create Date: 2026-09-09 22:29:55.075268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd299d5c1ae95'
down_revision = '980422e12355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_reviews', sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_scan_reviews_correlation_id'), 'scan_reviews', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_reviews_correlation_id'), table_name='scan_reviews')
    op.drop_column('scan_reviews', 'correlation_id')
    # ### end Alembic commands ###
