"""baseline schema

Revision ID: fa7cf1fb401e
Revises: 
Create Date: 2026-09-07 16:06:50.941899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa7cf1fb401e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("owner_type in ('submission','worksheet')", name='ck_media_owner_type'),
    sa.CheckConstraint("role in ('uploaded','dewarped','debug','checked')", name='ck_media_role'),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('schools',
    sa.Column('school_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('school_code')
    )
    op.create_table('skills',
    sa.Column('skill_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('skill_code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_from_number'), 'users', ['from_number'], unique=True)
    op.create_table('worksheet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheet_templates_name'), 'worksheet_templates', ['name'], unique=True)
    op.create_table('students',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('student_school_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_school_code'], ['schools.school_code'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('worksheets',
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('worksheet_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sheet_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('total_question_count', sa.Integer(), nullable=True),
    sa.Column('worksheet_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('worksheet_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("worksheet_category in ('practice','homework','test','omr')", name='ck_worksheets_category'),
    sa.ForeignKeyConstraint(['template_id'], ['worksheet_templates.id'], ),
    sa.PrimaryKeyConstraint('worksheet_id')
    )
    op.create_table('mastery_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.skill_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_history_skill_code'), 'mastery_history', ['skill_code'], unique=False)
    op.create_index(op.f('ix_mastery_history_student_id'), 'mastery_history', ['student_id'], unique=False)
    op.create_table('omr_answer_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_paper_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=True),
    sa.Column('answer_key_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("question_paper_code ~ '^[A-F]$'", name='ck_omr_answer_sets_code_valid'),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_name', 'question_paper_code')
    )
    op.create_index(op.f('ix_omr_answer_sets_template_name'), 'omr_answer_sets', ['template_name'], unique=False)
    op.create_index(op.f('ix_omr_answer_sets_worksheet_id'), 'omr_answer_sets', ['worksheet_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=True),
    sa.Column('skill_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.skill_code'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_worksheet_id'), 'questions', ['worksheet_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_guardians_from_number'), 'student_guardians', ['from_number'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    op.create_table('student_skill_mastery',
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.skill_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'skill_code')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('from_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("worksheet_category in ('practice','homework','test','omr')", name='ck_submissions_category'),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_submissions_worksheet_id'), 'submissions', ['worksheet_id'], unique=False)
    op.create_table('worksheet_pages',
    sa.Column('worksheet_page_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('first_question_index', sa.Integer(), nullable=False),
    sa.Column('last_question_index', sa.Integer(), nullable=False),
    sa.Column('expected_row_tag_count', sa.Integer(), nullable=False),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('worksheet_page_id'),
    sa.UniqueConstraint('worksheet_id', 'page_no')
    )
    op.create_table('attempts',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('skill_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bubble_confidence', sa.Float(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['skill_code'], ['skills.skill_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_attempts_question_id'), 'attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_attempts_student_id'), 'attempts', ['student_id'], unique=False)
    op.create_index(op.f('ix_attempts_submission_id'), 'attempts', ['submission_id'], unique=False)
    op.create_index(op.f('ix_attempts_worksheet_id'), 'attempts', ['worksheet_id'], unique=False)
    op.create_table('processing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_events_correlation_id'), 'processing_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_processing_events_submission_id'), 'processing_events', ['submission_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('option_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('question_paper_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('question_paper_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("question_paper_code ~ '^[A-F]$'", name='ck_qpv_code_valid'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_paper_variants_question_id'), 'question_paper_variants', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_paper_variants_worksheet_id'), 'question_paper_variants', ['worksheet_id'], unique=False)
    op.create_table('scan_reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('worksheet_id', sa.Integer(), nullable=True),
    sa.Column('detected_roll_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corrected_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_score', sa.Integer(), nullable=True),
    sa.Column('corrected_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('corrected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('failed','needs_review','corrected','approved')", name='ck_scan_reviews_status'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.worksheet_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_scan_reviews_submission_id'), 'scan_reviews', ['submission_id'], unique=False)
    op.create_index(op.f('ix_scan_reviews_worksheet_id'), 'scan_reviews', ['worksheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_reviews_worksheet_id'), table_name='scan_reviews')
    op.drop_index(op.f('ix_scan_reviews_submission_id'), table_name='scan_reviews')
    op.drop_table('scan_reviews')
    op.drop_index(op.f('ix_question_paper_variants_worksheet_id'), table_name='question_paper_variants')
    op.drop_index(op.f('ix_question_paper_variants_question_id'), table_name='question_paper_variants')
    op.drop_table('question_paper_variants')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_processing_events_submission_id'), table_name='processing_events')
    op.drop_index(op.f('ix_processing_events_correlation_id'), table_name='processing_events')
    op.drop_table('processing_events')
    op.drop_index(op.f('ix_attempts_worksheet_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_submission_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_student_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_question_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('worksheet_pages')
    op.drop_index(op.f('ix_submissions_worksheet_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('student_skill_mastery')
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_from_number'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_questions_worksheet_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_omr_answer_sets_worksheet_id'), table_name='omr_answer_sets')
    op.drop_index(op.f('ix_omr_answer_sets_template_name'), table_name='omr_answer_sets')
    op.drop_table('omr_answer_sets')
    op.drop_index(op.f('ix_mastery_history_student_id'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_skill_code'), table_name='mastery_history')
    op.drop_table('mastery_history')
    op.drop_table('worksheets')
    op.drop_table('students')
    op.drop_index(op.f('ix_worksheet_templates_name'), table_name='worksheet_templates')
    op.drop_table('worksheet_templates')
    op.drop_index(op.f('ix_users_from_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('schools')
    op.drop_table('media')
    # ### end Alembic commands ###
